### ISSUE TITLE
Shouldn't have to return response

### ISSUE THREAD

**Issue by TheByteSizeDev** [JeremyWhiteDev/daily-journal#10]
You probably don't need to return the response here. Not every function returns something, you only need to return the value if something is going to use the value that is returned from the function.

https://github.com/JeremyWhiteDev/daily-journal/blob/879f7d46cd1f8c0f7c13581ebf66f8adbf0989c8/scripts/dataAccess.js#L27-L43

**Comment by JeremyWhiteDev** [comment]
Ah right! Is returning the response something that could be used as a test or feedback to the user in case an http response code shows something went wrong? ie if the journal entry didn't post, don't re-render the page and instead have an alert? Obviously I'm not doing that in my code here. Just curious

**Comment by TheByteSizeDev** [comment]
Yes! You could create some kind of alert from the information that is true, especially if the outcome is that it returned an error.
